<? $tt='s:11:"(boston)/?$";s:35:"index.php?category_name=$matches[1]";s:64:"(atlanta/career-and-money)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";',


s:63:"(ttt/food-and-dining-ttt)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:46:"(ttt/food-and-dining-ttt)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:28:"(ttt/food-and-dining-ttt)/?$";s:35:"index.php?category_name=$matches[1]";
s:53:"(ttt/style-ttt)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:36:"(ttt/style-ttt)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:18:"(ttt/style-ttt)/?$";s:35:"index.php?category_name=$matches[1]";
s:61:"(ttt/entertainment-ttt)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:44:"(ttt/entertainment-ttt)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:26:"(ttt/entertainment-ttt)/?$";s:35:"index.php?category_name=$matches[1]";
s:54:"(ttt/travel-ttt)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:37:"(ttt/travel-ttt)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:19:"(ttt/travel-ttt)/?$";s:35:"index.php?category_name=$matches[1]";
s:57:"(ttt/nightlife-ttt)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:40:"(ttt/nightlife-ttt)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:22:"(ttt/nightlife-ttt)/?$";s:35:"index.php?category_name=$matches[1]";
s:63:"(ttt/home-and-garden-ttt)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:46:"(ttt/home-and-garden-ttt)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:28:"(ttt/home-and-garden-ttt)/?$";s:35:"index.php?category_name=$matches[1]";
s:71:"(ttt/electronics-and-gadgets-ttt)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:54:"(ttt/electronics-and-gadgets-ttt)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:36:"(ttt/electronics-and-gadgets-ttt)/?$";s:35:"index.php?category_name=$matches[1]";
s:54:"(ttt/dating-ttt)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:37:"(ttt/dating-ttt)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:19:"(ttt/dating-ttt)/?$";s:35:"index.php?category_name=$matches[1]";
s:66:"(ttt/sports-and-fitness-ttt)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:49:"(ttt/sports-and-fitness-ttt)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:31:"(ttt/sports-and-fitness-ttt)/?$";s:35:"index.php?category_name=$matches[1]";
s:64:"(ttt/career-and-money-ttt)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:47:"(ttt/career-and-money-ttt)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:29:"(ttt/career-and-money-ttt)/?$";s:35:"index.php?category_name=$matches[1]";
s:52:"(ttt/cars-ttt)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:35:"(ttt/cars-ttt)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:17:"(ttt/cars-ttt)/?$";s:35:"index.php?category_name=$matches[1]";
s:65:"(ttt/health-and-beauty-ttt)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:48:"(ttt/health-and-beauty-ttt)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:30:"(ttt/health-and-beauty-ttt)/?$";s:35:"index.php?category_name=$matches[1]";',$test);?