<?
$concat.="i:".$getterms[term_id].";a:12:{";	
$rule='s:53:"(uncategorized)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:36:"(uncategorized)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:18:"(uncategorized)/?$";s:35:"index.php?category_name=$matches[1]";';
$arr=array('Food &amp; Dining', 'Style', 'Entertainment', 'Travel', 'Nightlife', 'Home &amp; Garden', 'Electronics &amp; Gadgets', 'Dating', 'Sports &amp; Fitness', 'Career &amp; Money', 'Cars', 'Health &amp; Beauty');
		
$arr_slug=array("food-and-dining-".$cat_slug , "style-".$cat_slug , "entertainment-".$cat_slug , "travel-".$cat_slug , "nightlife-".$cat_slug , "home-and-garden-".$cat_slug , "electronics-and-gadgets-".$cat_slug , "dating-".$cat_slug , "sports-and-fitness-".$cat_slug , "career-and-money-".$cat_slug , "cars-".$cat_slug , "health-and-beauty-".$cat_slug);
$replacecontent='s:76:"(hyderabad/career-and-money-hyderabad)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:59:"(hyderabad/career-and-money-hyderabad)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:41:"(hyderabad/career-and-money-hyderabad)/?$";s:35:"index.php?category_name=$matches[1]";
s:64:"(hyderabad/cars-hyderabad)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:47:"(hyderabad/cars-hyderabad)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:29:"(hyderabad/cars-hyderabad)/?$";s:35:"index.php?category_name=$matches[1]";
s:66:"(hyderabad/dating-hyderabad)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:49:"(hyderabad/dating-hyderabad)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:31:"(hyderabad/dating-hyderabad)/?$";s:35:"index.php?category_name=$matches[1]";
s:83:"(hyderabad/electronics-and-gadgets-hyderabad)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:66:"(hyderabad/electronics-and-gadgets-hyderabad)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:48:"(hyderabad/electronics-and-gadgets-hyderabad)/?$";s:35:"index.php?category_name=$matches[1]";
s:73:"(hyderabad/entertainment-hyderabad)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:56:"(hyderabad/entertainment-hyderabad)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:38:"(hyderabad/entertainment-hyderabad)/?$";s:35:"index.php?category_name=$matches[1]";
s:75:"(hyderabad/food-and-dining-hyderabad)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:58:"(hyderabad/food-and-dining-hyderabad)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:40:"(hyderabad/food-and-dining-hyderabad)/?$";s:35:"index.php?category_name=$matches[1]";
s:77:"(hyderabad/health-and-beauty-hyderabad)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:60:"(hyderabad/health-and-beauty-hyderabad)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:42:"(hyderabad/health-and-beauty-hyderabad)/?$";s:35:"index.php?category_name=$matches[1]";
s:75:"(hyderabad/home-and-garden-hyderabad)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:58:"(hyderabad/home-and-garden-hyderabad)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:40:"(hyderabad/home-and-garden-hyderabad)/?$";s:35:"index.php?category_name=$matches[1]";s:49:"(hyderabad)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:32:"(hyderabad)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:14:"(hyderabad)/?$";s:35:"index.php?category_name=$matches[1]";
s:69:"(hyderabad/nightlife-hyderabad)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:52:"(hyderabad/nightlife-hyderabad)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:34:"(hyderabad/nightlife-hyderabad)/?$";s:35:"index.php?category_name=$matches[1]";
s:78:"(hyderabad/sports-and-fitness-hyderabad)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:61:"(hyderabad/sports-and-fitness-hyderabad)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:43:"(hyderabad/sports-and-fitness-hyderabad)/?$";s:35:"index.php?category_name=$matches[1]";
s:65:"(hyderabad/style-hyderabad)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:48:"(hyderabad/style-hyderabad)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:30:"(hyderabad/style-hyderabad)/?$";s:35:"index.php?category_name=$matches[1]";
s:66:"(hyderabad/travel-hyderabad)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:49:"(hyderabad/travel-hyderabad)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:31:"(hyderabad/travel-hyderabad)/?$";s:35:"index.php?category_name=$matches[1]";';
$explode_string=
's:53:"(uncategorized)/(?:feed/)?(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:36:"(uncategorized)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:18:"(uncategorized)/?$";s:35:"index.php?category_name=$matches[1]";';
?>